name: jackgordonplane
favicon: null
layout_spectrum: 0.24504
typography_spectrum: 0.86564
title: HOME
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#acacac'
    - '#575757'
    - '#888888'
    - '#2f2f2f'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
