name: jackgordonplane
favicon: null
layout_spectrum: 0.72549
typography_spectrum: 0.8848
title: 'Professional Writer | Serious Reader | World Traveller |'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8fc7f8'
    - '#ffffff'
    - '#c5d7eb'
    - '#3c74b1'
    - '#014681'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
