name: jackgordonplane
favicon: null
layout_spectrum: 0.47632
typography_spectrum: 1
title: JACK GORDON PLANE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8fc7f8'
    - '#ffffff'
    - '#c5d7eb'
    - '#3c74b1'
    - '#014681'
  brandStrength: 0
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
